services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: hireflow_backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/hireflow_db

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: hireflow_frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped

  db:
    image: postgres:17
    container_name: hireflow_postgres

    environment:
      POSTGRES_DB: hireflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - hireflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hireflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  hireflow_postgres_data: