# Generated by Django 6.0.3 on 2026-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_apply_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_via',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
