# Generated by Django 6.0.3 on 2026-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_applied_via'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied_via',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_via',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
