# Generated by Django 6.0.3 on 2026-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
